services:
  spring-boot-app:
    build: .
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=xcale'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=xcale'
    ports:
      - '5432:5432'
